name: pyhrm
channels:
  - defaults
dependencies:
  - attrs=19.3.0=py_0
  - backcall=0.2.0=py_0
  - blas=1.0=mkl
  - bleach=3.1.5=py_0
  - ca-certificates=2020.6.24=0
  - certifi=2020.6.20=py38_0
  - colorama=0.4.3=py_0
  - cycler=0.10.0=py38_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py38_0
  - freetype=2.10.2=hd328e21_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - importlib-metadata=1.7.0=py38_0
  - importlib_metadata=1.7.0=0
  - intel-openmp=2020.1=216
  - ipykernel=5.3.0=py38h5ca1d4c_0
  - ipython=7.16.1=py38h5ca1d4c_0
  - ipython_genutils=0.2.0=py38_0
  - ipywidgets=7.5.1=py_0
  - jedi=0.17.1=py38_0
  - jinja2=2.11.2=py_0
  - joblib=0.16.0=py_0
  - jpeg=9b=hb83a4c4_2
  - jsonschema=3.2.0=py38_0
  - jupyter=1.0.0=py38_7
  - jupyter_client=6.1.5=py_0
  - jupyter_console=6.1.0=py_0
  - jupyter_core=4.6.3=py38_0
  - kiwisolver=1.2.0=py38h74a9793_0
  - libpng=1.6.37=h2a8f88b_0
  - libsodium=1.0.18=h62dcd97_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.1.1=py38he774522_0
  - matplotlib=3.2.2=0
  - matplotlib-base=3.2.2=py38h64f37c6_0
  - mistune=0.8.4=py38he774522_1000
  - mkl=2020.1=216
  - mkl-service=2.3.0=py38hb782905_0
  - mkl_fft=1.1.0=py38h45dec08_0
  - mkl_random=1.1.1=py38h47e9c7a_0
  - msys2-conda-epoch=20160418=1
  - nbconvert=5.6.1=py38_0
  - nbformat=5.0.7=py_0
  - notebook=6.0.3=py38_0
  - numpy=1.18.5=py38h6530119_0
  - numpy-base=1.18.5=py38hc3f5095_0
  - openssl=1.1.1g=he774522_0
  - packaging=20.4=py_0
  - pandas=1.0.5=py38h47e9c7a_0
  - pandoc=2.9.2.1=0
  - pandocfilters=1.4.2=py38_1
  - parso=0.7.0=py_0
  - pickleshare=0.7.5=py38_1000
  - pip=20.1.1=py38_1
  - prometheus_client=0.8.0=py_0
  - prompt-toolkit=3.0.5=py_0
  - prompt_toolkit=3.0.5=0
  - pygments=2.6.1=py_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py38ha925a31_4
  - pyrsistent=0.16.0=py38he774522_0
  - python=3.8.3=he1778fa_2
  - python-dateutil=2.8.1=py_0
  - pytz=2020.1=py_0
  - pywin32=227=py38he774522_1
  - pywinpty=0.5.7=py38_0
  - pyzmq=19.0.1=py38ha925a31_1
  - qt=5.9.7=vc14h73c81de_0
  - qtconsole=4.7.5=py_0
  - qtpy=1.9.0=py_0
  - scikit-learn=0.23.1=py38h25d0782_0
  - scipy=1.5.0=py38h9439919_0
  - send2trash=1.5.0=py38_0
  - setuptools=47.3.1=py38_0
  - sip=4.19.13=py38ha925a31_0
  - six=1.15.0=py_0
  - sqlite=3.32.3=h2a8f88b_0
  - terminado=0.8.3=py38_0
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tornado=6.0.4=py38he774522_1
  - traitlets=4.3.3=py38_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_3
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py38_1
  - wheel=0.34.2=py38_0
  - widgetsnbextension=3.5.1=py38_0
  - wincertstore=0.2=py38_0
  - winpty=0.4.3=4
  - zeromq=4.3.2=ha925a31_2
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h62dcd97_4
prefix: C:\Miniconda3\envs\pyhrm

